# -*- coding: utf-8 -*-
"""Accident_Predictor_Feature_Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qxbnnMkm6TG85wPBKsX3Vdsu_AkfiB8
"""

!pip install opendatasets -q

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import time
import pandas as pd
import opendatasets as od

od.download("https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents")

df = pd.read_csv("/content/us-accidents/US_Accidents_March23.csv",
                 nrows = 5000000
                 )

df.head()

df.info()

print(df.isnull().sum())

(df == 0).sum()

df_cleaned = df.dropna()

print("Cleaned Dataset Shape: ", df_cleaned.shape)

print("\nRemaining Null Values:")
print(df_cleaned.isnull().sum())

df_cleaned.to_csv('/content/cleaned_dataset.csv', index=False)

features = [
    'ID',
    'Source',
    'Severity',
    'Start_Time',
    'End_Time',
    'Start_Lat',
    'Start_Lng',
    'Distance(mi)',
    'Street',
    'City',
    'County',
    'State',
    'Country',
    'Weather_Timestamp',
    'Temperature(F)',
    'Wind_Chill(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Direction',
    'Wind_Speed(mph)',
    'Precipitation(in)',
    'Weather_Condition',
    'Bump',
    'Crossing',
    'Give_Way',
    'Junction',
    'No_Exit',
    'Railway',
    'Roundabout',
    'Station',
    'Stop',
    'Traffic_Calming',
    'Traffic_Signal',
    'Turning_Loop',
    'Sunrise_Sunset'
]

df_final = df_cleaned[features]

output_file = "accident_final.csv"

df_final.to_csv(output_file, index= False)

df_final.head()

df_final.info()

print(df_final.isnull().sum())

(df_final == 0).sum()

X_features = [
    'ID',
    'Source',
    'Start_Time',
    'End_Time',
    'Start_Lat',
    'Start_Lng',
    'Distance(mi)',
    'Street',
    'City',
    'County',
    'State',
    'Country',
    'Weather_Timestamp',
    'Temperature(F)',
    'Wind_Chill(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Direction',
    'Wind_Speed(mph)',
    'Precipitation(in)',
    'Weather_Condition',
    'Bump',
    'Crossing',
    'Give_Way',
    'Junction',
    'No_Exit',
    'Railway',
    'Roundabout',
    'Station',
    'Stop',
    'Traffic_Calming',
    'Traffic_Signal',
    'Turning_Loop',
    'Sunrise_Sunset'
]

X = df_final[X_features]
y = df_final["Severity"]

X

y

